<?php

use TreptowKolleg\ORM\Model\EntityManager;
use TreptowKolleg\ORM\Model\Repository;
use TreptowKolleg\ORM\ORM;

require_once 'vendor/autoload.php';

class Pupil
{

    #[ORM\Id]
    #[ORM\AutoGenerated]
    #[ORM\Column(type: ORM\Types::Integer)]
    private int $id;

    #[ORM\Column(length: 50, nullable: true)]
    private string $firstname;

    #[ORM\Column(length: 50)]
    private string $lastname;

    public function getId(): int
    {
        return $this->id;
    }

    public function getFirstname(): string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): void
    {
        $this->firstname = $firstname;
    }

    public function getLastname(): string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): void
    {
        $this->lastname = $lastname;
    }

}



$em = new EntityManager();
$em->createTable(Pupil::class);

$pupil = new Pupil();
$pupil->setFirstname('John');
$pupil->setLastname('Doe');

$ben = (new Repository(Pupil::class))->findOneBy(['firstname' => 'Benjamin']);
if($ben) {
    $ben->setLastname('Voigt');
    $em->persist($ben);
}

$em->persist($pupil);
$em->flush();

