<?php

namespace TreptowKolleg\ORM\Field;

use TreptowKolleg\ORM\Attribute as DB;
use TreptowKolleg\ORM\Attribute\Type;

/**
 * Trait IdField
 *
 * Dieser Trait fügt einer Klasse ein eindeutiges Identifikationsfeld (`id`) hinzu.
 * Das `id`-Feld wird als automatisch generierte Ganzzahl (`Integer`) gespeichert und dient
 * als Primärschlüssel in der Datenbank.
 *
 * Attribute:
 * - `#[DB\Id]`: Markiert das Feld als Primärschlüssel.
 * - `#[DB\AutoGenerated]`: Gibt an, dass der Wert automatisch von der Datenbank generiert wird.
 * - `#[DB\Column(type: Type::Integer)]`: Definiert den Datentyp des Feldes als Integer.
 *
 * Methoden:
 * - `getId()`: Gibt den Wert des `id`-Feldes zurück oder `null`, falls noch keine ID zugewiesen wurde.
 *
 * Beispiele für die Nutzung:
 * ```php
 * $id = $entity->getId();
 * ```
 */
trait IdField
{

    /**
     * @var int|null $id
     *
     * Die eindeutige Identifikationsnummer des Datensatzes. Kann `null` sein,
     * wenn der Datensatz noch nicht gespeichert und die ID daher noch nicht generiert wurde.
     */
    #[DB\Id]
    #[DB\AutoGenerated]
    #[DB\Column(type: Type::Integer)]
    private ?int $id = null;

    /**
     * Gibt die eindeutige Identifikationsnummer zurück.
     *
     * @return int|null Die ID des Datensatzes oder `null`, falls die ID noch nicht generiert wurde.
     */
    public function getId(): ?int
    {
        return $this->id;
    }

}