<?php

namespace TreptowKolleg\ORM\Field;

use TreptowKolleg\ORM\Attribute as DB;
use TreptowKolleg\ORM\Attribute\Type;

trait IdField
{

    #[DB\Id]
    #[DB\AutoGenerated]
    #[DB\Column(type: Type::Integer)]
    private ?int $id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

}